barnehagefakta.get - ERROR - Could not connect to http://barnehagefakta.no/api/barnehage/1026295, try again later? HTTPConnectionPool(host='barnehagefakta.no', port=80): Max retries exceeded with url: /api/barnehage/1026295 (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x109cca910>: Failed to establish a new connection: [Errno 51] Network is unreachable',))
